spring:
  application:
    name: solnax

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/solnax
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Europe/Zurich
    show-sql: false

  cache:
    type: caffeine

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.rose.solnax: DEBUG
    org.hibernate.SQL: INFO
    org.flywaydb.core: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

solaredge:
  modbus:
    host: 192.168.0.90
    port: 1502
    slaveId: 1
    connectTimeoutMs: 3000
tesla-ble:
  host: http://192.168.0.90:8080
  white: VINWHITE
  black: VINBLACK
  max-charge-level: 80 #%
  min-charge-level: 60 #%
  power-buffer: 500 # watts safety margin to avoid grid import
  default-voltage: 230 # volts
  default-phases: 3
  min-amps: 5 # minimum charge amps (3-phase)
  max-amps: 16 # maximum charge amps (3-phase)

TWCManager:
  host: http://192.168.0.89

shelly:
  em3:
    # Shared defaults – can be overridden per device
    connect-timeout: 3s
    read-timeout: 5s

    devices:
      heater:
        host: 192.168.0.50
      kitchen:
        host: 192.168.0.51
      charger:
        host: 192.168.0.52
      sauna:
        host: 192.168.0.53