version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spring-postgres
    environment:
      POSTGRES_DB: solnax
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - spring-network
    restart: unless-stopped
networks:
  spring-network:
    driver: bridge